---
name: Build and Test
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
env:
  glob1: glob-val1
  glob2: glob-val2

jobs:
  build:
    name: Build the Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout external libs
        uses: actions/checkout@v2
        with:
          repository: opsgang/libs
          ref: refs/tags/0.0.16
          path: 'opsgang/libs'
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: envs
        run: env | sort
      - name: test env var concat
        run: echo "var3=${{ env.var3 }}"; echo "---"; echo "var4=${{ env.var4 }}"
        env:
          var1: "val1"
          var2: "val2"
          var3: "${{ env.var1 }} and ${{ env.var2 }}"
          var4: "${{ env.glob1 }} and ${{ env.glob2 }}"
      - name: PR id
        run: echo $GITHUB_PR_ID
        env:
          GITHUB_PR_ID: "${{ github.event.number }}"
      - name: PR id on merge
        run: echo $PR
        env:
          PR: ${{ steps.findPr.outputs.pr }}

