---
name: Build and Test
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build the Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: PR id
        run: echo $GITHUB_PR_ID > docker-image.txt
        env:
          GITHUB_PR_ID: "${{ github.event.number }}"
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: docker-image-${{ github.event.number }}
          path: docker-image.txt
          retention-days: 14
